version: '3.8'

services:
  nc-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-password
      - MYSQL_PASSWORD=your-password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nc-cache:
    image: redis:alpine
    restart: always

  nextcloud:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_HOST=nc-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your-password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXTCLOUD_TRUSTED_DOMAINS=your-nextcloud-domain.com
      - OVERWRITEHOST=your-nextcloud-domain.com
    depends_on:
      - nc-db
      - redis

  nc-nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - nextcloud-data:/var/www/html:ro
    environment:
      - NEXTCLOUD_HOST=your-nextcloud-domain.com
    depends_on:
      - app
    ports:
      - "80:80"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=your-secret-key

volumes:
  nextcloud-db:
  nextcloud-data:
