version: '3.8'

services:
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    environment:
      - SEAFILE_SERVER_HOSTNAME=seafile.example.com
    volumes:
      - seafile-data:/shared
      - seafile-config:/opt/seafile/conf

  rclone:
    image: rclone/rclone:latest
    volumes:
      - seafile-data:/seafile-data

volumes:
  seafile-data:
